  _target_: ai4co_gnn.models.zoo.POMO

  normalization: 'gauss'

  policy:
    _target_: rl4co.models.zoo.am.policy.AttentionModelPolicy
    embed_dim: 128
    init_embedding:
      _target_: rl4co.models.nn.env_embeddings.init.MTVRPInitEmbedding
      embed_dim: ${model.policy.embed_dim}
    context_embedding:
      _target_: rl4co.models.nn.env_embeddings.context.MTVRPContext
      embed_dim: ${model.policy.embed_dim}
    dynamic_embedding:
      _target_: rl4co.models.nn.env_embeddings.dynamic.StaticEmbedding
    encoder:
      _target_: rl4co.models.zoo.am.encoder.AttentionModelEncoder
      num_layers: 3
      init_embedding:
        _target_: rl4co.models.nn.env_embeddings.init.MTVRPInitEmbedding
        embed_dim: ${model.policy.embed_dim}
    decoder:
      _target_: rl4co.models.zoo.am.decoder.AttentionModelDecoder
      use_graph_context: false
      context_embedding:
        _target_: rl4co.models.nn.env_embeddings.context.MTVRPContext
        embed_dim: ${model.policy.embed_dim}
      dynamic_embedding:
        _target_: rl4co.models.nn.env_embeddings.dynamic.StaticEmbedding
